# Generated by Django 6.0 on 2026-01-01 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='error_keyword',
            field=models.CharField(blank=True, help_text='Main error message or keyword', max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='module',
            field=models.CharField(blank=True, help_text='Odoo module name, e.g. account, stock', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='odoo_version',
            field=models.CharField(blank=True, help_text='e.g. 14, 15, 16, 17, 17.0', max_length=20),
        ),
    ]
