# Generated by Django 6.0 on 2026-01-02 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_error_keyword_post_module_post_odoo_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='error_keyword',
        ),
        migrations.RemoveField(
            model_name='post',
            name='featured_image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='module',
        ),
        migrations.RemoveField(
            model_name='post',
            name='odoo_version',
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.CreateModel(
            name='PostBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('paragraph', 'Paragraph'), ('heading', 'Heading'), ('image', 'Image'), ('code', 'Code'), ('quote', 'Quote'), ('divider', 'Divider')], max_length=20)),
                ('order', models.PositiveIntegerField()),
                ('text', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='post_blocks/')),
                ('language', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='posts.post')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
