# Generated by Django 6.0 on 2026-01-02 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_post_content_remove_post_error_keyword_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='error_code',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='module',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='odoo_version',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
