# Generated by Django 6.0 on 2026-01-02 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_error_code_post_module_post_odoo_version'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='error_code',
            new_name='error_keyword',
        ),
    ]
