# Generated by Django 6.0 on 2026-01-02 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_rename_error_code_post_error_keyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='postblock',
            name='align',
            field=models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='center', max_length=10),
        ),
        migrations.AddField(
            model_name='postblock',
            name='width',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
