# Generated by Django 6.0 on 2026-01-02 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_postblock_align_postblock_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='postblock',
            name='content_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postblock',
            name='html_content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='postblock',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20),
        ),
    ]
