# Generated by Django 6.0 on 2026-01-02 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_postblock_content_json_postblock_html_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postblock',
            name='content_json',
        ),
        migrations.RemoveField(
            model_name='postblock',
            name='html_content',
        ),
        migrations.RemoveField(
            model_name='postblock',
            name='status',
        ),
        migrations.AddField(
            model_name='post',
            name='content_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='html_content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20),
        ),
    ]
