# Generated by Django 6.0 on 2026-01-11 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_remove_postblock_post_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='post',
            name='posts_post_slug_59b922_idx',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='posts_post_status_79fb4e_idx',
        ),
        migrations.AddField(
            model_name='post',
            name='error_keyword',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='module',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='odoo_version',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_json',
            field=models.JSONField(blank=True, help_text='Raw Tiptap JSON', null=True),
        ),
    ]
